default: &default
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: jack
  password: password

development:
  <<: *default
  database: skeleton_development

test: &test
  <<: *default
  database: skeleton_test
